title: "Sangbin Lee"
description: "Ph.D. Student · Department of Architecture and Architectural Engineering, [SCIAL](https://smartinfra.snu.ac.kr), [DAAE](https://daae.snu.ac.kr), [SNU](https://www.snu.ac.kr)"
logo: /assets/img/profile.jpg
show_downloads: false
theme: jekyll-theme-minimal
